[Appearance]
color_scheme_path=~/.local/share/color-schemes/noctalia.colors
icon_theme=breeze-dark
custom_palette=true
style=Breeze

[Fonts]
fixed="Noto Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular,0,0"
general="Noto Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular,0,0"

