# Default ChickenOS config.
# You can override its settings in this file.
# If you remove this line, you will use the stock config instead.
# If you do not want updates, copy the config and remove the imports.
include /usr/share/chickenos/kitty/config.conf
