FROM localhost/chickenos:disk

RUN install -Dm755 /dev/stdin /usr/bin/chickenos-nested <<'EOF'
#!/usr/bin/env bash
ln -sf "/run-host/$WAYLAND_DISPLAY" "/run/user/1000/$WAYLAND_DISPLAY"
CHICKENOS_SESSION_COMMAND=/usr/bin/umbriel chickenos-session &
journalctl -fu nested.service -n0 | grep -m1 disconnected
EOF

RUN cat > /etc/systemd/system/nested.service <<'EOF'
[Unit]
Wants=user@1000.service
After=user@1000.service

[Install]
WantedBy=multi-user.target

[Service]
Environment=XDG_RUNTIME_DIR=/run/user/1000
ExecStopPost=+/usr/bin/systemctl exit
ExecStart=/usr/bin/chickenos-nested
PassEnvironment=WAYLAND_DISPLAY
WorkingDirectory=/home/user
User=user

EOF

RUN systemctl mask auditd audit-rules bootloader-update systemd-resolved \
    && systemctl enable nested.service

ENTRYPOINT ["/sbin/init", "--unit=multi-user.target"]