FROM localhost/chickenos:disk

RUN install -Dm755 /dev/stdin /usr/bin/chickenos-nested <<'EOF'
#!/usr/bin/env bash
CHICKENOS_SESSION_COMMAND=/usr/bin/umbriel chickenos-session & 
journalctl -fu nested.service -n0 | grep -m1 disconnected 
EOF

RUN cat > /etc/systemd/system/nested.service <<'EOF'
[Install]
WantedBy=multi-user.target

[Service]
Environment=XDG_RUNTIME_DIR=/host-runtime
ExecStopPost=+/usr/bin/systemctl exit
ExecStart=/usr/bin/chickenos-nested
PassEnvironment=WAYLAND_DISPLAY
WorkingDirectory=/home/user
User=user
EOF

RUN systemctl mask auditd audit-rules bootloader-update systemd-resolved \
    && systemctl enable nested.service

ENTRYPOINT ["/sbin/init", "--unit=multi-user.target"]