FROM localhost/chickenos:base

# Autologin user
RUN install -Dm440 /dev/stdin /etc/sudoers.d/chickenos <<'EOF'
%wheel ALL=(ALL:ALL) NOPASSWD: ALL
EOF

RUN cat >> /etc/greetd/config.toml <<'EOF'
[initial_session]
command = "/usr/bin/chickenos-session"
user = "user"
EOF

RUN useradd -m -G wheel user && echo 'user:user' | chpasswd 

# Init user keyring
RUN cat > /etc/systemd/user/user-keyring.service <<'EOF'
[Unit]
Wants=gnome-keyring-daemon.socket
After=gnome-keyring-daemon.socket

[Install]
WantedBy=default.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c "printf '\0' | /usr/bin/gnome-keyring-daemon --unlock"
EOF

RUN systemctl --global enable user-keyring.service
