# Ctrl+Click to open links 
mouse_map left click ungrabbed mouse_handle_click selection prompt
mouse_map ctrl+left release ungrabbed mouse_handle_click link

# Right Click Copy
mouse_map right press ungrabbed combine : copy_to_clipboard : clear_selection
map ctrl+shift+c combine : copy_to_clipboard : clear_selection
map ctrl+shift+0 change_font_size all 0

# Appearance
window_padding_width 0 10
confirm_os_window_close 0
copy_on_select no
cursor_shape beam

# General
enabled_layouts splits:split_axis=auto
shell fish
