[include]
# Default ChickenOS config.
# You can override its settings in this file.
# If you remove this line, you will use the stock config instead.
# If you do not want updates, copy the contents of the directory here.
files = [ "/usr/share/chickenos/umbriel/config.toml" ] 
