name: builder

on:
  workflow_call:
    inputs:
      variant:
        default: main
        required: true
        type: string

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_TAG: "${{ inputs.variant }}"
jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-24.04
    steps:
      - name: Mount BTRFS for podman storage
        uses: ublue-os/container-storage-action@main

      - name: Prepare environment
        run: |
          echo "IMAGE_TAG=${IMAGE_TAG,,}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "IMAGE_FULL=${IMAGE_REGISTRY,,}/${IMAGE_NAME,,}:${IMAGE_TAG,,}" >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          SECUREBOOT_KEY: ${{ secrets.SECUREBOOT_KEY }}
        with:
          push: true
          file: Containerfile
          tags: ${{ env.IMAGE_FULL }}
          secret-envs: secureboot=SECUREBOOT_KEY
          build-args: VARIANT=${{ inputs.variant }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.9.0

      - name: Sign container image
        run: cosign sign -y --key env://COSIGN_KEY  ${{ env.IMAGE_FULL }}
        env:
          COSIGN_EXPERIMENTAL: false
          TAGS: ${{ steps.push.outputs.digest }}
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
